baseURL = "https://juliusrueckin.github.io/"
languageCode = "en-us"
title = "Data Management and Data Exploration"
preserveTaxonomyNames = true

[menu]
	[[menu.mainmenu]]
		identifier = "chair"
		name = "Chair"
		url = "/"
		weight = 1

	[[menu.mainmenu]]
		identifier = "team"
		name = "Team"
		url = "/team/"
		weight = 2

	[[menu.mainmenu]]
		identifier = "teaching"
		name = "Teaching"
		url = "/teaching/"
		weight = 3

	[[menu.mainmenu]]
		identifier = "publications"
		name = "Publications"
		url = "/publications/"
		weight = 7

	[[menu.mainmenu]]
		identifier = "research"
		name = "Research"
		url = "/research/"
		weight = 4

	[[menu.mainmenu]]
		identifier = "projects"
		name = "Projects"
		url = "/projects/"
		weight = 5

	[[menu.mainmenu]]
		identifier = "data_science"
		name = "Data Science"
		url = "/data_science/"
		weight = 6

	[[menu.mainmenu]]
		identifier = "B-IT"
		name = "B-IT"
		url = "http://bit.uni-bonn.de"
		weight = 8

[taxonomies]
  conference = "conference"
  year = "year"
  publication_type = "publication_type"
  research_area = "research_area"
  author = "authors"