baseURL = "https://juliusrueckin.github.io/"
languageCode = "en-us"
title = "Data Management and Data Exploration"
preserveTaxonomyNames = true

[menu]
	[[menu.mainmenu]]
		identifier = "chair"
		name = "Chair"
		url = "/"
		weight = 1

	[[menu.mainmenu]]
		identifier = "team"
		name = "Team"
		url = "/team/"
		weight = 2

	[[menu.mainmenu]]
		identifier = "publications"
		name = "Publications"
		url = "/publications/"
		weight = 3

	[[menu.mainmenu]]
		identifier = "data_and_code"
		name = "Data & Code"
		url = "/data_and_code/"
		weight = 4

	[[menu.mainmenu]]
		identifier = "projects"
		name = "Projects"
		url = "/projects/"
		weight = 5

[taxonomies]
  conference = "conference"
  year = "year"
  publication_type = "publication_type"
  research_area = "research_area"
  author = "authors"